'use client';
import React from "react";
import { useState, useEffect } from "react";
import { emit } from "process";
import Sidebar from "@/components/sidebar";
import { useSearchParams, useRouter } from "next/navigation";
import axios from "axios";
import { request } from "http";
import Cookies from 'js-cookie';
import Swal from 'sweetalert2';
import PatientInformation from "@/components/patientInformation";
import FamilyInformation from "@/components/familyInformation";

const GeneralRecord = () => {
    const [error, setError] = useState("");
    const [loading, setLoading] = useState(false);
    const router = useRouter();
    const [rmNumber, setRmNumber] = useState("Generating RM Number");
    const searchParams = useSearchParams();
    const recordType = searchParams.get("type");
    const [patientData, setPatientData] = useState({});
    const [familyData, setFamilyData] = useState({});
    const handlePatientUpdate = (data: any) => setPatientData(data);
    const handleFamilyUpdate = (data: any) => setFamilyData(data);

    const fetchRmNumber = async () => {
        try {
            const token = Cookies.get('access_token');

            if (!token) {
                setRmNumber("Unauthorized");
                return;
            }

            const response = await axios.get(
                `http://localhost:5000/api/medical-record/rm-number?type=${recordType}`,
                { headers: { Authorization: `Bearer ${token}` } }
            );

            setRmNumber(response.data.next_rm_number);
        } catch (error) {
            console.error("Error fetching RM number:", error);
            setRmNumber("Failed to generate RM Number");
        }
    };

    useEffect(() => {
        fetchRmNumber();
    }, [recordType]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setLoading(true);
        try {
            const token = Cookies.get('access_token');
            if (!token) {
                alert("Unauthorized. Please log in.");
                return;
            }
            const payload = {
                ...patientData,
                ...familyData,
                record_number: rmNumber,
                record_type: recordType,

            };
            const response = await axios.post("http://localhost:5000/api/medical-record/add-general", payload, {
                headers: { Authorization: `Bearer ${token}` }
            });
            if (response.status === 201) {
                Swal.fire({
                    title: "Success",
                    text: "Data KB NADI berhasil disimpan!",
                    icon: "success",
                    timer: 2000,
                    confirmButtonColor: "#739072"
                });
                fetchRmNumber();

            } router.push('/medical-record');
        } catch (err: any) {
            console.error(err);
            setLoading(false);
            const errorMessage = err.response?.data?.msg || "Something went wrong";
            Swal.fire({
                title: "Gagal Menyimpan!",
                text: errorMessage,
                icon: "error",
                confirmButtonColor: "#739072",
            });
            setError(errorMessage);
        }
    };
    return (
        <div className="min-h-screen flex bg-[#FDFEF9]">
            <div className="flex-1 flex flex-col w-full ml-10 mt-7">
                <div className="flex flex-col gap-2">
                    <input
                        type="text"
                        value={rmNumber}
                        readOnly
                        className="bg-transparent font-mono font-bold cursor-not-allowed focus:outline-none text-3xl text-[#4F6F52] w-full"
                    />
                    <p className="text-[10px] text-gray-400">*Generated by the system</p>
                </div>
                <PatientInformation
                    record_type={recordType || "Keluarga Berencana"}
                    onDataChange={handlePatientUpdate}
                />
                <FamilyInformation
                    onDataChange={handleFamilyUpdate}
                />


                <div className="flex justify-center gap-4 mt-10">
                    <button
                        onClick={handleSubmit}
                        type="submit"
                        className="px-8 py-2 bg-[#739072] text-white rounded-full hover:bg-[#4F6F52] shadow-lg transition font-bold cursor-pointer"
                    >
                        Save Record
                    </button>
                </div>
            </div>
        </div>

    )

}
export default GeneralRecord;
