'use client';
import React from "react";
import { useState, useEffect } from "react";
import { emit } from "process";
import { useSearchParams } from "next/navigation";
import axios from "axios";
import { request } from "http";
import Cookies from 'js-cookie';
import PatientInformation from "@/components/patientInformation";
import FamilyInformation from "@/components/familyInformation";

const ImmunizationRecord = () => {
    const [rmNumber, setRmNumber] = useState("Generating RM Number");
    const searchParams = useSearchParams();

    const [vaccineType, setVaccineType] = useState("");
    const [doseNumber, setDoseNumber] = useState("");

    const recordType = searchParams.get("type");
    const [patientData, setPatientData] = useState({});
    const [familyData, setFamilyData] = useState({});

    const handlePatientUpdate = (data: any) => setPatientData(data);
    const handleFamilyUpdate = (data: any) => setFamilyData(data);
    useEffect(() => {
        const fetchRmNumber = async () => {
            try {
                const token = Cookies.get('access_token');

                if (!token) {
                    setRmNumber("Unauthorized");
                    return;
                }
                const response = await axios.get(
                    `http://localhost:5000/api/medical-record/rm-number?type=${recordType}`,
                    { headers: { Authorization: `Bearer ${token}` } }
                );

                setRmNumber(response.data.next_rm_number);
            } catch (error) {
                console.error("Error fetching RM number:", error);
                setRmNumber("Failed to generate RM Number");
            }
        };

        if (recordType) fetchRmNumber();
    }, [recordType]);

    const handleSubmit = async () => {
        try {
            const token = Cookies.get('access_token');
            if (!token) {
                alert("Unauthorized. Please log in.");
                return;
            }
            const payload = {
                ...patientData,
                ...familyData,
                record_number: rmNumber,
                record_type: recordType,


            };
            const response = await axios.post("http://localhost:5000/api/medical-record/add-pregnancy", payload, {
                headers: { Authorization: `Bearer ${token}` }
            });
            alert("Data Berhasil Disimpan ke Database!");

        } catch (err) {
            console.error(err);
            alert("Gagal konek ke server!");
        }
    };
    return (
        <div className="min-h-screen flex bg-[#FDFEF9]">
            <div className="flex-1 flex flex-col w-full ml-10 mt-7">
                <div className="flex flex-col gap-2">
                    <input
                        type="text"
                        value={rmNumber}
                        readOnly
                        className="bg-transparent font-mono font-bold cursor-not-allowed focus:outline-none text-3xl text-[#4F6F52] w-full"
                    />
                    <p className="text-[10px] text-gray-400">*Generated by the system</p>
                </div>
                <PatientInformation
                    record_type={recordType || "Kehamilan"}
                    onDataChange={handlePatientUpdate}
                />
                <FamilyInformation
                    onDataChange={handleFamilyUpdate}
                />

                <div className="flex flex-col gap-0">
                    <h2 className="text-md text-[#4F6F52] mt-10 underline leading-none !font-lexend">Immunization Track</h2>
                    <hr className="mt-0"></hr>
                </div>
                <div className="flex flex-col mt-4 gap-y-4">
                    <div className="flex flex-row w-full gap-20 justify-between">
                        <div className="flex flex-col flex-1 gap-y-1 ">
                            Vaccine Type
                            <input type="text" name="vaccineType" id="vaccineType" className="w-full h-8 rounded-md bg-white drop-shadow-lg border border-gray-300 focus:outline-none focus:ring-2" />
                        </div>
                        <div className="flex flex-col  flex-1">
                            Dose Number
                            <input type="number" name="doseNumber" id="doseNumber" className="w-full h-8 rounded-md bg-white drop-shadow-lg border border-gray-300 focus:outline-none focus:ring-2" />
                        </div>
                    </div>

                </div>

                <div className="flex justify-center gap-4 mt-10">
                    <button
                        onClick={handleSubmit}
                        type="submit"
                        className="px-8 py-2 bg-[#739072] text-white rounded-full hover:bg-[#4F6F52] shadow-lg transition font-bold cursor-pointer"
                    >
                        Save Record
                    </button>
                </div>
            </div>
        </div>

    )

}
export default ImmunizationRecord;
