import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: "RME App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={inter.className}
      >
  
          {children}
     
      </body>
    </html>
  );
}
