import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "RME App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body
        className={`antialiased`}
      >
          <NextTopLoader />
          {children}
     
      </body>
    </html>
  );
}
